# Generated by Django 5.1 on 2024-08-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='image',
            field=models.ImageField(null=True, upload_to='generated_images/'),
        ),
    ]
