# Generated by Django 5.1 on 2024-08-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0002_imagemetadata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemetadata',
            name='image',
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='image_generated',
            field=models.ImageField(null=True, upload_to='images_generated/'),
        ),
    ]
